**Importation des bibliothèques**

In [ ]:
import tensorflow
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout,Conv1D, MaxPooling1D,Flatten,BatchNormalization
from sklearn.model_selection import train_test_split
import numpy 
import pandas as pd
import matplotlib.pyplot as plt

from tensorflow.keras.callbacks import ModelCheckpoint, LearningRateScheduler


import tensorflow as tf
print(tf.__version__)

import numpy as np
print(np.__version__)

numpy.random.seed(2)
import pandas as pd

2.8.0
1.21.5


**Configurer les GPUs**

In [ ]:
config = tensorflow.compat.v1.ConfigProto()
sess = tensorflow.compat.v1.Session(config=config)


**Importation de la base**

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving stand_norm_e1.txt to stand_norm_e1 (1).txt
Saving stand_norm_e2.txt to stand_norm_e2 (2).txt
Saving y2_e1.txt to y2_e1 (1).txt
User uploaded file "stand_norm_e1.txt" with length 1082418 bytes
User uploaded file "stand_norm_e2.txt" with length 1088310 bytes
User uploaded file "y2_e1.txt" with length 344050 bytes


In [ ]:

dataset_e1= pd.read_csv("stand_norm_e1.txt",delimiter=" ",header=None)
dataset_e1=numpy.array(dataset_e1,float)

X_e1 = dataset_e1[:,:8]
#m=np.max(X_e1)
print(X_e1.shape)
dataset_e2= pd.read_csv("stand_norm_e2.txt",delimiter=" ",header=None)
dataset_e2=numpy.array(dataset_e2,float)

X_e2 = dataset_e2[:,:8]
#n=np.max(X_e2)
#X_e2=X_e2/n
print(X_e2.shape)
x_train_test=np.zeros((X_e1.shape[0],X_e1.shape[1],2))
x_train_test[:,:,0]=X_e1
x_train_test[:,:,1]=X_e2
print(x_train_test.shape)
#print(x_test.shape)
dataset_output= pd.read_csv("y2_e1.txt",delimiter=" ",header=None)
dataset_output=numpy.array(dataset_output,float)
dataset_output_new= dataset_output.reshape(dataset_output.shape[0], )
print(dataset_output_new.shape)

(13762, 8)
(13762, 8)
(13762, 8, 2)
(13762,)


In [ ]:
x_train_test[:,:,0]

array([[1.93978268e+02, 9.89658300e+00, 2.02883500e+01, ...,
        1.23907620e+02, 6.62235000e-01, 9.66716000e-01],
       [8.21718810e+01, 1.85822300e+00, 1.79525440e+01, ...,
        1.70642080e+01, 6.49830000e-01, 1.72596200e+00],
       [3.26893179e+03, 6.52433300e+00, 1.85320570e+01, ...,
        1.00173500e+03, 6.37607000e-01, 3.63161000e-01],
       ...,
       [1.93845034e+02, 4.31289000e-01, 7.66381500e+00, ...,
        1.48119304e+02, 1.11113900e+00, 7.66170000e-01],
       [5.37608964e+02, 1.15022900e+00, 1.45061190e+01, ...,
        1.80209238e+02, 1.11802400e+00, 6.40931000e-01],
       [1.53551504e+02, 4.51115000e-01, 6.77274800e+00, ...,
        9.98209850e+01, 1.12499300e+00, 4.70517000e-01]])

In [ ]:
df1 = pd.DataFrame(X_e1)
df1


0          1           2           3           4  \
0       193.978268   9.896583   20.288350    6.804330   13.081385   
1        82.171881   1.858223   17.952544    1.654808   10.642098   
2      3268.931792   6.524333   18.532057   11.778797  100.361604   
3       187.713618  12.989908   50.031645   10.465349    6.657465   
4      8523.951526  12.144298  110.111264  129.507430  115.632581   
...            ...        ...         ...         ...         ...   
13757   182.257718   1.269828    5.957268   12.407817   20.102809   
13758   240.699826   0.988268    7.495868    2.000583   70.765327   
13759   193.845034   0.431289    7.663815    5.322897   12.307730   
13760   537.608964   1.150229   14.506119   16.052488  115.690890   
13761   153.551504   0.451115    6.772748    5.757678   20.748978   

                 5         6         7  
0       123.907620  0.662235  0.966716  
1        17.064208  0.649830  1.725962  
2      1001.735001  0.637607  0.363161  
3       107.569252  0.625563  1.568878  
4      8036.555953  0.613699  0.632804  
...            ...       ...       ...  
13757   122.519995  1.097614  0.642058  
13758   157.449779  1.104336  0.634507  
13759   148.119304  1.111139  0.766170  
13760   180.209238  1.118024  0.640931  
13761    99.820985  1.124993  0.470517  

[13762 rows x 8 columns]

In [ ]:
df2 = pd.DataFrame(X_e2)
df2

0          1          2           3           4           5  \
0      163.215520   9.042817  17.174985   16.798999   17.999821   62.198898   
1      139.694651   9.746471  14.166749   11.845185   52.160073   11.776174   
2      510.818945   8.066165  23.923719   10.373002   10.858827  227.597232   
3      276.786558   2.186425  23.365242    7.404066   21.185753  180.645072   
4      339.535036  13.373983  98.357123    7.541251   51.019504  149.243177   
...           ...        ...        ...         ...         ...         ...   
13757  384.036565   0.991592  11.327074   14.492147  152.389177  104.836575   
13758  481.610815   0.943346  15.631620   14.146275  122.985482  117.904093   
13759  159.326878   0.831945   5.816673   13.090606   23.983004   95.604650   
13760  881.386462   1.816735  14.278827  115.200025  147.679472  282.411404   
13761  198.749977   0.529931   8.645401   17.199167   67.056447  105.319030   

              6         7  
0      0.662235  1.030338  
1      0.649830  1.128905  
2      0.637607  0.810661  
3      0.625563  1.455839  
4      0.613699  1.526440  
...         ...       ...  
13757  1.097614  0.538693  
13758  1.104336  0.499516  
13759  1.111139  0.537590  
13760  1.118024  0.502287  
13761  1.124993  0.540046  

[13762 rows x 8 columns]

In [ ]:
label = pd.DataFrame(dataset_output)
label

0
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
...    ...
13757  0.0
13758  0.0
13759  0.0
13760  0.0
13761  0.0

[13762 rows x 1 columns]

**Répartition entre l'apprentissage et test**

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_train_test, dataset_output_new, test_size=0.15, random_state=42)

In [ ]:
x_train_new=x_train
x_test_new=x_test

**Préparation des sorties du modèle**

In [ ]:
print(x_train_new.shape)
print(y_train.shape)

Y_train_new = tensorflow.keras.utils.to_categorical( y_train)
Y_test_new = tensorflow.keras.utils.to_categorical(y_test)
print(Y_train_new.shape)

(11697, 8, 2)
(11697,)
(11697, 3)


**Préparation des entrées du modèle**

In [ ]:
print (x_train_new.shape)
x_train_new=x_train_new.reshape(x_train_new.shape[0],  x_train_new.shape[1], 2)
x_test_new = x_test_new.reshape(x_test_new.shape[0], x_test_new.shape[1],2 )
print (x_train_new.shape)

(11697, 8, 2)
(11697, 8, 2)


**Construction du modèle**

In [ ]:
nsamples, nx, ny = x_train_new.shape
d2_train_dataset = x_train_new.reshape((nsamples,nx*ny))

In [ ]:
nsamples, nx, ny = x_test_new.shape
d2_test_dataset = x_test_new.reshape((nsamples,nx*ny))

### **Random Forest Classifier**

In [ ]:
from sklearn.ensemble import RandomForestClassifier


In [ ]:
rfc = RandomForestClassifier(n_estimators=150,criterion='gini',
                             random_state=42, min_samples_split = 4,
                             min_samples_leaf= 3, max_features = "log2",
                             oob_score = True, verbose = 9, 
                             class_weight = "balanced",
                             min_weight_fraction_leaf = 0.00,
                             n_jobs = 10, warm_start = True,
                             )

rfc.fit(d2_train_dataset,Y_train_new)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:766: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  'class_weight presets "balanced" or '
[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.


building tree 1 of 150
building tree 2 of 150
building tree 3 of 150
building tree 4 of 150building tree 5 of 150
building tree 6 of 150
building tree 7 of 150
building tree 8 of 150
building tree 9 of 150
building tree 10 of 150

building tree 11 of 150
building tree 12 of 150
building tree 13 of 150
building tree 14 of 150
building tree 15 of 150building tree 16 of 150

building tree 17 of 150
building tree 18 of 150
building tree 19 of 150
building tree 20 of 150
building tree 21 of 150
building tree 22 of 150
building tree 23 of 150
building tree 24 of 150
building tree 25 of 150building tree 26 of 150
building tree 27 of 150
building tree 28 of 150
building tree 29 of 150

building tree 30 of 150


[Parallel(n_jobs=10)]: Done  12 tasks      | elapsed:    0.8s


building tree 31 of 150
building tree 32 of 150
building tree 33 of 150
building tree 34 of 150
building tree 35 of 150
building tree 36 of 150
building tree 37 of 150
building tree 38 of 150
building tree 39 of 150
building tree 40 of 150


[Parallel(n_jobs=10)]: Done  30 tasks      | elapsed:    1.4s


building tree 41 of 150
building tree 42 of 150
building tree 43 of 150
building tree 44 of 150
building tree 45 of 150
building tree 46 of 150
building tree 47 of 150building tree 48 of 150

building tree 49 of 150
building tree 50 of 150
building tree 51 of 150
building tree 52 of 150
building tree 53 of 150
building tree 54 of 150
building tree 55 of 150
building tree 56 of 150
building tree 57 of 150
building tree 58 of 150
building tree 59 of 150
building tree 60 of 150


[Parallel(n_jobs=10)]: Done  52 tasks      | elapsed:    2.6s


building tree 61 of 150
building tree 62 of 150
building tree 63 of 150
building tree 64 of 150
building tree 65 of 150
building tree 66 of 150
building tree 67 of 150
building tree 68 of 150
building tree 69 of 150
building tree 70 of 150
building tree 71 of 150
building tree 72 of 150
building tree 73 of 150
building tree 74 of 150
building tree 75 of 150
building tree 76 of 150
building tree 77 of 150
building tree 78 of 150
building tree 79 of 150
building tree 80 of 150
building tree 81 of 150
building tree 82 of 150
building tree 83 of 150
building tree 84 of 150
building tree 85 of 150
building tree 86 of 150
building tree 87 of 150
building tree 88 of 150
building tree 89 of 150
building tree 90 of 150


[Parallel(n_jobs=10)]: Done  78 tasks      | elapsed:    3.6s


building tree 91 of 150
building tree 92 of 150
building tree 93 of 150
building tree 94 of 150building tree 95 of 150
building tree 96 of 150

building tree 97 of 150
building tree 98 of 150
building tree 99 of 150
building tree 100 of 150
building tree 101 of 150
building tree 102 of 150
building tree 103 of 150
building tree 104 of 150
building tree 105 of 150
building tree 106 of 150
building tree 107 of 150
building tree 108 of 150
building tree 109 of 150
building tree 110 of 150
building tree 111 of 150
building tree 112 of 150
building tree 113 of 150
building tree 114 of 150
building tree 115 of 150
building tree 116 of 150
building tree 117 of 150
building tree 118 of 150


[Parallel(n_jobs=10)]: Done 108 tasks      | elapsed:    4.9s


building tree 119 of 150
building tree 120 of 150
building tree 121 of 150
building tree 122 of 150
building tree 123 of 150
building tree 124 of 150
building tree 125 of 150
building tree 126 of 150
building tree 127 of 150building tree 128 of 150

building tree 129 of 150
building tree 130 of 150
building tree 131 of 150
building tree 132 of 150building tree 133 of 150

building tree 134 of 150
building tree 135 of 150
building tree 136 of 150
building tree 137 of 150
building tree 138 of 150
building tree 139 of 150
building tree 140 of 150
building tree 141 of 150
building tree 142 of 150
building tree 143 of 150
building tree 144 of 150
building tree 145 of 150
building tree 146 of 150
building tree 147 of 150
building tree 148 of 150
building tree 149 of 150
building tree 150 of 150


[Parallel(n_jobs=10)]: Done 148 out of 150 | elapsed:    6.6s remaining:    0.1s
[Parallel(n_jobs=10)]: Done 150 out of 150 | elapsed:    6.6s finished


RandomForestClassifier(class_weight='balanced', max_features='log2',
                       min_samples_leaf=3, min_samples_split=4,
                       n_estimators=150, n_jobs=10, oob_score=True,
                       random_state=42, verbose=9, warm_start=True)

In [ ]:
predicted_output = rfc.predict(d2_test_dataset)


[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done  12 tasks      | elapsed:    0.0s
[Parallel(n_jobs=10)]: Done  30 tasks      | elapsed:    0.0s
[Parallel(n_jobs=10)]: Done  52 tasks      | elapsed:    0.1s
[Parallel(n_jobs=10)]: Done  78 tasks      | elapsed:    0.1s
[Parallel(n_jobs=10)]: Done 108 tasks      | elapsed:    0.1s
[Parallel(n_jobs=10)]: Done 148 out of 150 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=10)]: Done 150 out of 150 | elapsed:    0.2s finished


**Effectuer l'apprentissage**

**Evalutations**

In [ ]:
y_pred = np.empty((predicted_output.shape[0]))
y_test = np.empty((predicted_output.shape[0]))
for i in range(predicted_output.shape[0]):   
    y_pred[i]=np.argmax(predicted_output[i])
    y_test[i]=np.argmax(Y_test_new[i])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score, precision_score, recall_score
threshold_confusion = 0.5
print ("\nConfusion matrix:  Custom threshold (for positive) of " +str(threshold_confusion))       
confusion = confusion_matrix(y_test,  y_pred)
print (confusion)


Confusion matrix:  Custom threshold (for positive) of 0.5
[[851 128   1]
 [ 73 982   1]
 [  2   1  26]]


In [ ]:
print("The accuracy score on this random test-set is  :", accuracy_score(y_test,  y_pred) )
recall=recall_score(y_test,  y_pred, average=None)
av_recall=sum(recall)/3
print("recall",recall, "the avreage recall is ",av_recall)
precision=precision_score(y_test,  y_pred,average=None)
av_precision=sum(precision)/3

print("precision",precision,"the avreage precision is ",av_precision)

F1_score=(2*av_precision*av_recall)/(av_precision+av_recall)
print("F1_score",F1_score)

The accuracy score on this random test-set is  : 0.9002421307506053
recall [0.86836735 0.92992424 0.89655172] the avreage recall is  0.8982811045003163
precision [0.91900648 0.88388839 0.92857143] the avreage precision is  0.9104887656306513
F1_score 0.9043437393908061


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

         0.0       0.92      0.87      0.89       980
         1.0       0.88      0.93      0.91      1056
         2.0       0.93      0.90      0.91        29

    accuracy                           0.90      2065
   macro avg       0.91      0.90      0.90      2065
weighted avg       0.90      0.90      0.90      2065

